### ISSUE TITLE
iOS build error "cocoapods version is out-of-date"

### ISSUE THREAD

**Issue by ZaLiTHkA** [dpa99c/cordova-plugin-firebasex-test#10]
greetings.. I've been trying for about a week now to get the `cordova-plugin-firebasex` plugin working in an Ionic 5 app with Angular 9, but I'm still having no luck.

the issue with **my** environment is that I don't have access to macOS, at least, not a recent enough version to build for the current iPadOS and iPhoneOS platforms. which means I'm limited to building iOS projects through Ionic AppFlow.

since I wasn't getting anywhere with my *own* project, I thought I'd try building *this* example project instead, just to see what happens. I cloned it locally, updated all project naming and ID references, dropped my own Android `google-services.json` and 
iOS `GoogleService-Info.plist` into `www/` and ran it in my local Android emulator with no issues.

in order to test the iOS side, I added the most basic Ionic wrapper info, and tried to run a build in AppFlow Package. but unfortunately I'm still not winning...

**note**: I did also run into issue dpa99c/cordova-plugin-firebasex#323 at one point in this process, so I have also removed the `#dev` branch reference from the plugin source URL, which made it install commit 753e52 (current `master` as of the time of writing).

I also found an article in Ionic's public support FAQ that provides [a workaround to update CocoaPods](https://ionic.zendesk.com/hc/en-us/articles/360010049673-Managing-plugins-using-cocoapods-in-Ionic-Pro), but looking at the order of the above logs, it doesn't seem to be helping.

anyways, the furthest I've managed to get is the `cordova platform add ios` command, which fails as follows:

```
[16:07:01]: --------------------------------------
[16:07:01]: --- Step: cordova platform add ios ---
[16:07:01]: --------------------------------------
[16:07:01]: $ cordova platform add ios
[16:07:01]: ▸ Running command: /Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile/update_pods.sh /Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile
[16:07:01]: ▸ Using cordova-fetch for cordova-ios@^6.0.0
[16:07:01]: ▸ Adding ios project...
[16:07:02]: ▸ Creating Cordova project for the iOS platform:
[16:07:02]: ▸ Path: platforms/ios
[16:07:02]: ▸ Package: com.nortech.dashboardmobile
[16:07:02]: ▸ Name: LIVE
[16:07:02]: ▸ iOS project created with cordova-ios@6.1.1
[16:07:02]: ▸ Installing "cordova-plugin-customfcmreceiver" for ios
[16:07:03]: ▸ Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
[16:07:03]: ▸ Installing "cordova-plugin-whitelist" for ios
[16:07:03]: ▸ Adding cordova-plugin-whitelist to package.json
[16:07:03]: ▸ Discovered saved plugin "cordova-plugin-firebasex". Adding it to the project
[16:08:02]: ▸ Installing "cordova-plugin-firebasex" for ios
[16:08:02]: ▸ Installing "cordova-plugin-androidx" for ios
[16:08:02]: ▸ Installing "cordova-plugin-androidx-adapter" for ios
[16:08:05]: ▸ Failed to install 'cordova-plugin-firebasex': Error: cocoapods version is out-of-date - please update to cocoapods@^1.9.1 - current version: 1.7.5
[16:08:05]: ▸ at checkCocoapodsVersion (/Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile/plugins/cordova-plugin-firebasex/scripts/ios/before_plugin_install.js:21:15)
[16:08:05]: ▸ at module.exports (/Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile/plugins/cordova-plugin-firebasex/scripts/ios/before_plugin_install.js:7:5)
[16:08:05]: ▸ at runScriptViaModuleLoader (/usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:181:32)
[16:08:05]: ▸ at runScript (/usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:157:16)
[16:08:05]: ▸ at /usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:125:20
[16:08:05]: ▸ at processTicksAndRejections (internal/process/task_queues.js:97:5)
[16:08:05]: ▸ Failed to restore plugin "cordova-plugin-firebasex" from config.xml. You might need to try adding it again. Error: Error: cocoapods version is out-of-date - please update to cocoapods@^1.9.1 - current version: 1.7.5
[16:08:05]: ▸ Discovered saved plugin "cordova-custom-config". Adding it to the project
[16:08:05]: ▸ Installing "cordova-custom-config" for ios
[16:08:06]: ▸ Adding cordova-custom-config to package.json
[16:08:06]: ▸ Discovered saved plugin "cordova-plugin-dialogs". Adding it to the project
[16:08:11]: ▸ Installing "cordova-plugin-dialogs" for ios
[16:08:11]: ▸ Adding cordova-plugin-dialogs to package.json
[16:08:11]: ▸ Discovered saved plugin "cordova-plugin-enable-multidex". Adding it to the project
[16:08:11]: ▸ Installing "cordova-plugin-enable-multidex" for ios
[16:08:12]: ▸ Adding cordova-plugin-enable-multidex to package.json
[16:08:12]: ▸ Discovered saved plugin "cordova-plugin-hello-c". Adding it to the project
[16:08:12]: ▸ Installing "cordova-plugin-hello-c" for ios
[16:08:12]: ▸ Adding cordova-plugin-hello-c to package.json
[16:08:12]: ▸ Overwriting existing resource file at platforms/ios/LIVE/Resources/res/ios/sound/blackberry.caf
[16:08:12]: ▸ Overwriting existing resource file at platforms/ios/LIVE/Resources/res/ios/sound/crystal.caf
[16:08:12]: ▸ Overwriting existing resource file at platforms/ios/LIVE/Resources/res/ios/sound/msn.caf
[16:08:12]: ▸ Overwriting existing resource file at platforms/ios/LIVE/Resources/res/ios/pn-actions.json
[16:08:12]: ▸ cordova-plugin-firebasex: Preparing Firebase on iOS
[16:08:12]: ▸ cordova-plugin-firebasex: Applied IOS_STRIP_DEBUG to Podfile
[16:08:12]: ▸ Running command: /Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile/run_pods.sh /Users/ionic/builds/nortech-international/RnD/software/common-dashboard-mobile
```

@dpa99c, really sorry to bug you, but please can you tell me: am I simply screwed without having a Mac myself, or am I perhaps doing something else wrong here?

**Comment by ZaLiTHkA** [comment]
just now I discovered a [build stack version breakdown](https://ionicframework.com/docs/appflow/build-stacks) in the Ionic AppFlow docs, where I see a different MacOS build environment that already has CocoaPods version 1.9.3 installed.

running a build in the `iOS - v2020.08` stack (instead of the `iOS - Xcode 11 (Preferred)` stack I was using) with the same commit seems to solve the build issue.

so, the good news is this is not an issue for this project then.. :)
